CC=gcc
CFLAGS=-Wall
COMPILE=-c -g
project:main.o hash.o graph.o llist.o vertices.o heapsort.o minimumSpanningTree.o checkTriangleInequality.o
	$(CC) -o project main.o llist.o hash.o vertices.o graph.o heapsort.o checkTriangleInequality.o minimumSpanningTree.o

main.o:main.c hash.o graph.o vertices.o main.h
	$(CC) $(COMPILE) main.c

hash.o:hash.c hash.h main.h
	$(CC) $(COMPILE) hash.c

graph.o:graph.c graph.h main.h
	$(CC) $(COMPILE) graph.c

vertices.o:vertices.c vertices.h main.h
	$(CC) $(COMPILE) vertices.c

heapsort.o:heapsort.c heapsort.h main.h
	$(CC) $(COMPILE) heapsort.c

minimumSpanningTree.o:minimumSpanningTree.c minimumSpanningTree.h main.h
	$(CC) $(COMPILE) minimumSpanningTree.c

checkTriangleInequality.o:checkTriangleInequality.c checkTriangleInequality.h main.h
	$(CC) $(COMPILE) checkTriangleInequality.c
clean:
	rm -rf *.o project
